config/routes.rb
Rails.application.routes.draw do

  root 'programs#index'
  
  resources :programs
  resources :users
  resources :episode_markers do
    get 'toggle_completed', on: :member
  end

end

app/models/episode.rb
# == Schema Information
#
# Table name: episodes
#
#  id             :integer          not null, primary key
#  title          :string
#  description    :text
#  time           :integer
#  part_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  sequence_index :integer
#
# Indexes
#
#  index_episodes_on_part_id  (part_id)
#

class Episode < ActiveRecord::Base
  belongs_to :part
  validates :title, presence: true
  validates :part_id, presence: true
end

app/models/episode_marker.rb
# == Schema Information
#
# Table name: episode_markers
#
#  id             :integer          not null, primary key
#  part_marker_id :integer
#  episode_id     :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  completed      :boolean          default(FALSE)
#  elapsed        :integer          default(0)
#
# Indexes
#
#  index_episode_markers_on_episode_id      (episode_id)
#  index_episode_markers_on_part_marker_id  (part_marker_id)
#

class EpisodeMarker < ActiveRecord::Base
  belongs_to :part_marker
  belongs_to :episode
  validates :part_marker_id, presence: true
  validates :episode_id, presence: true
end

app/models/part.rb
# == Schema Information
#
# Table name: parts
#
#  id         :integer          not null, primary key
#  title      :string
#  program_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_parts_on_program_id  (program_id)
#

class Part < ActiveRecord::Base
  belongs_to :program
  has_many :episodes
  validates :title, presence: true
  validates :program_id, presence: true
end

app/models/part_marker.rb
# == Schema Information
#
# Table name: part_markers
#
#  id                :integer          not null, primary key
#  program_marker_id :integer
#  part_id           :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_part_markers_on_part_id            (part_id)
#  index_part_markers_on_program_marker_id  (program_marker_id)
#

class PartMarker < ActiveRecord::Base
  has_many :episode_markers
  belongs_to :program_marker
  belongs_to :part
  validates :program_marker_id, presence: true
  validates :part_id, presence: true
end

app/models/program.rb
# == Schema Information
#
# Table name: programs
#
#  id            :integer          not null, primary key
#  title         :string
#  description   :text
#  format        :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  default_image :string
#

class Program < ActiveRecord::Base
  has_many :parts
  validates :title, presence: true

  def placeholder_image
  	'placeholder.jpg'
  end
end

app/models/program_marker.rb
# == Schema Information
#
# Table name: program_markers
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  program_id :integer
#  notes      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_program_markers_on_program_id  (program_id)
#  index_program_markers_on_user_id     (user_id)
#

class ProgramMarker < ActiveRecord::Base
  has_many :part_markers
  belongs_to :user
  belongs_to :program
  validates :user_id, presence: true
  validates :program_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_many :program_markers
  validates :name, presence: true
end

app/models/watch_marker.rb
class WatchMarker < ActiveRecord::Base
  has_many :watch_marker_parts
  belongs_to :user
  belongs_to :program
  validates :user_id, presence: true
  validates :program_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  
end

app/controllers/episode_markers_controller.rb
class EpisodeMarkersController < ApplicationController
  
  def update
    episode_marker_service = EpisodeMarkerService.new(params)
    timecode_saved = episode_marker_service.validate_timecode
    @part = episode_marker_service.get_part
    @part_marker = episode_marker_service.get_part_marker
    if timecode_saved
      trigger_ajax_refresh
    else
      flash[:danger] = "Please enter a valid timecode"
    end
  end
  
  def toggle_completed
    episode_marker_service = EpisodeMarkerService.new(params)
    episode_marker_service.toggle_completed
    @part_marker = episode_marker_service.get_part_marker    
    trigger_ajax_refresh
  end
  
  
  private
  
    def trigger_ajax_refresh
      respond_to do |format|
        format.html { redirect_to @user }
        format.js
      end
    end
  
  
end

app/controllers/program_markers_controller.rb
class ProgramMarkersController < ApplicationController
  
  def update
    @part_marker = PartMarker.find(1)
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  
  def index
    @programs = Program.all.sort_by { |program| program.title }
  end
  
  def show
    @program = Program.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all.sort_by { |user| user.name }
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  #def format_as_timecode(sec)
  #  seconds = sec % 60
  #  minutes = (sec / 60) % 60
  #  hours = sec / 3600
  #  
  #  if hours > 0
  #    "%d:%02d:%02d" % [hours, minutes, seconds]
  #  else
  #    "%d:%02d" % [minutes, seconds]
  #  end
  #end
  
  #def parse_timecode(string)
  #  parts = string.split(":").map(&:to_f)
  #  parts = [0] + parts if parts.length == 2
  #  hours, minutes, seconds = parts
  #  seconds = hours * 3600 + minutes * 60 + seconds
  #  seconds.to_i
  #end
  
  #def percent_as_decimal(string)
  #  percent = string.tr('%', '')
  #  decimal = percent.to_f / 100
  #end
  
  def total_time_in_part(part)
    @part = part
    @episodes = @part.episodes
    @episode_times = Array.new
    @episodes.each do |episode|
      @episode_times << episode.time
    end
    @episode_times.reduce(:+)
  end
  
  def total_time_in_program(program)
    @program = program
    @parts = @program.parts
    @part_times = Array.new
    @parts.each do |part|
      @part_times << total_time_in_part(part)
    end
    @part_times.reduce(:+)
  end
  
  def time_elapsed_in_part(part_marker)
    @part_marker = part_marker
    @episode_markers = @part_marker.episode_markers
    @episode_elapsed_times = Array.new
    @episode_markers.each do |episode_marker|
      @episode_elapsed_times << episode_marker.elapsed
    end
    @episode_elapsed_times.reduce(:+)
  end
  
  def time_elapsed_in_program(program_marker)
    @program_marker = program_marker
    @part_markers = @program_marker.part_markers
    @part_elapsed_times = Array.new
    @part_markers.each do |part_marker|
      @part_elapsed_times << time_elapsed_in_part(part_marker)
    end
    @part_elapsed_times.reduce(:+)
  end
end

app/helpers/episode_markers_helper.rb
module EpisodeMarkersHelper
end

app/helpers/program_markers_helper.rb
module ProgramMarkersHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/episode_markers/toggle_completed.js.erb
$("#ajax-part-episodes-<%= @part_marker.id %>").html("<%= escape_javascript(render('users/episode_markers', part_marker: @part_marker)) %>");

EnterEchoView();

app/views/episode_markers/update.js.erb
/*<% flash.each do |type, message| %>
  $('#flash_messages').html('<%= message.html_safe %>')
<% end %>*/

$("#ajax-part-episodes-<%= @part_marker.id %>").html("<%= escape_javascript(render('users/episode_markers', part_marker: @part_marker)) %>");

/*this part isn't blocking or throwing an error anymore, but it's not actually updating either...*/
$("ajax-part-marker-<%= @part_marker.id %>").html("<%= escape_javascript(render('users/part_marker', part_marker: @part_marker)) %>");

EnterEchoView();

app/views/layouts/_header.html.erb
<div class="site-hd">
  <div class="site-hd-logo">Watchlist</div>
  <div class="site-hd-nav">
    <ul class="mainNav">
      <li><%= link_to "Programs", programs_path %></li>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "MyWatchlist", '#' %></li>
    </ul>
  </div>
</div>
<div id="flash_messages">
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: "flash #{name}" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watchlist</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <%= yield %>

</body>
</html>

app/views/programs/index.html.erb
<h1>Program Index</h1>
<p>These are all the programs you have to chose from!</p>

<div class="blocks blocks_3up">
  <% @programs.each do |program| %>
    <div>
      <div class="imageWrapper">
        <% if !program.default_image.blank? %>
          <%= image_tag program.default_image, alt: program.title %>
        <% else %>
          <%= image_tag program.placeholder_image, alt: program.title %>
        <% end %>
      </div>
      <div class="hdg hdg_2"><%= program.title %></div>
      <div>
        <%= link_to "Details", program_path(program), class: "btn" %>
        <%= link_to "Watch", '#', class: "btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/programs/show.html.erb
<h1><%= @program.title %></h1>
<%= link_to "Back to Program Index", programs_path, class: "btn" %>
<ul>
  <% @program.parts.each do |part| %>
    <li class="index-item-part">
      <%= "#{part.title} (#{pluralize(part.episodes.count, 'episode')})" %>
      <ul>
        <li>
          <% part.episodes.each do |episode| %>
            <span><%= episode.title %></span>
          <% end %>
        </li>
      </ul>
    </li>
  <% end %>
</ul>

app/views/users/_episode_markers.html.erb
<% part_marker.episode_markers.joins(:episode)
              .order("episodes.sequence_index asc").each do |episode_marker| %>
  <% @episode = Episode.find(episode_marker.episode_id) %>
  <div class="index-item-part">
    <div class="inline-block">
      <span><%= episode_marker.completed %></span>
    </div>
    <div class="inline-block">  
      <div class="marker">
        <span class="marker-index"><%= @episode.sequence_index %></span>
        <%= link_to @episode.sequence_index, 
            toggle_completed_episode_marker_path(episode_marker), 
            class: "marker-trigger", remote: true %>
        <div class="marker-status 
                    marker-status_episode marker-status_<%= ((episode_marker.elapsed.to_f / 
                    @episode.time) * 100).round %>of100">
          <span class="marker-index"><%= @episode.sequence_index %></span>
        </div>
      </div>
    </div>
    <div class="inline-block">
      <%= form_for episode_marker, remote: true do |f| %>
        <%= f.text_field :elapsed, id: "js-echo_#{episode_marker.id}", class: "js-echo", 
              value: FormatService.format_as_timecode(episode_marker.elapsed) %>
        <span id="js-enter_<%= episode_marker.id %>" class="js-enter" contentEditable="true">
          <%= FormatService.format_as_timecode(episode_marker.elapsed) %>
        </span> / <%= FormatService.format_as_timecode(@episode.time) %>
        <%= f.submit "Save", id: "js-echo-submit_#{episode_marker.id}", class: "js-echo-submit btn" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_episodes.html.erb
<% part_marker.episode_markers.joins(:episode).order("episodes.sequence_index asc").each do |episode_marker| %>
  <% @episode = Episode.find(episode_marker.episode_id) %>
  <div class="index-item-part">
    <div class="inline-block">  
      <div class="marker">
        <span class="marker-index"><%= @episode.sequence_index %></span>
        <%= link_to @episode.sequence_index, toggle_completed_episode_marker_path(episode_marker), class: "marker-trigger", remote: true %>
        <div class="marker-status marker-status_episode marker-status_<%= ((episode_marker.elapsed.to_f / @episode.time) * 100).round %>of100">
          <span class="marker-index"><%= @episode.sequence_index %></span>
        </div>
      </div>
    </div>
    <div class="inline-block">
      <%= form_for episode_marker, remote: true do |f| %>
        <%= f.text_field :elapsed, class: "js-echo_#{episode_marker.id}", value: format_as_timecode(episode_marker.elapsed) %>
        <span class="js-enter_<%= episode_marker.id %>"><%= format_as_timecode(episode_marker.elapsed) %></span> / <%= format_as_timecode(@episode.time) %>
        <%= f.submit "Save", class: "js-echo-submit_#{episode_marker.id} btn" %>
      <% end %>
    </div>
  </div>

<script>
  /*$(".js-enter_<%= episode_marker.id %>").val($(".js-enter_<%= episode_marker.id %>").html());
  console.log($(".js-enter_<%= episode_marker.id %>").val());
  $(".js-enter_<%= episode_marker.id %>").on("change", function() {
    console.log($(this).val());
    $(".js-echo_<%= episode_marker.id %>").val($(this).html());
  });*/
  //This script is not currently working -- putting this feature on hold
</script>

<% end %>

app/views/users/_part_marker.html.erb
                <%= @part.title %> 
                      (<%= FormatService.format_as_timecode(time_elapsed_in_part(part_marker).to_f) %> / 
                       <%= FormatService.format_as_timecode(total_time_in_part(@part)) %>)
                <div class="index-item-controls">
                  <span class="marker">
                    <div class="marker-status 
                                marker-status_part marker-status_<%= ((time_elapsed_in_part(part_marker).to_f / 
                                total_time_in_part(@part)) * 100).round %>of100"></div>
                  </span>
                </div>

app/views/users/index.html.erb
<h1>User Index</h1>

<ul class="index">
  <% @users.each do |user| %>
    <li class="index-item">
      <div class="index-item-title">
        <%= link_to user.name, user_path(user) %>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p>These are the shows that <%= @user.name %> is watching.</p>
<%= link_to "Back to User Index", users_path, class: "btn" %>
<ul class="index">
  <% @user.program_markers.each do |program_marker| %>
    <li class="js-accordion index-item">
      <% @program = Program.find(program_marker.program_id) %>
      <div class="index-item-title">
        <span class="js-trigger"><%= @program.title %> (<%= FormatService.format_as_timecode(time_elapsed_in_program(program_marker).to_f) %> / <%= FormatService.format_as_timecode(total_time_in_program(@program)) %>)</span>
        <div class="index-item-controls">
          <div class="marker js-trigger">
            <div class="marker-status marker-status_program marker-status_<%= ((time_elapsed_in_program(program_marker).to_f / total_time_in_program(@program)) * 100).round %>of100"></div>
          </div>
        </div>
      </div>
      <div class="js-panel">
        <ul class="index-item-part">
          <% program_marker.part_markers.each do |part_marker| %>
            <li class="index-item">
              <% @part = Part.find(part_marker.part_id) %>
              <div id="ajax-part-marker-<%= part_marker.id %>" class="index-item-title">
                <%= render ('users/part_marker'), part_marker: part_marker %>
              </div>
              <ul>
                <li id="ajax-part-episodes-<%= part_marker.id %>" >
                  <%= render ('users/episode_markers'), part_marker: part_marker %>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </li>
  <% end %>
</ul>